export default {
  mainLabel: "Abylay & Aisha",
  weddingDate: "2022-07-16T17:00:00",
  weddingCoordinates: [43.257369, 76.952748],
  weddingMapUrl: "https://go.2gis.com/dcpj9",
  uzatuDate: "2022-07-02T17:00:00",
  uzatuCoordinates: [50.290213, 57.115187],
  uzatuMapUrl: "https://go.2gis.com/y38195",
  writeMyWA: "https://wa.me/77056707891",
  content: {
    ru: {
      label: "Летнее торжество",
      dear: "Дорогие",
      and: "и",
      dearMale: "Дорогой",
      dearFemale: "Дорогая",
      inviteText1: "Приглашаем Вас на наше семейное торжество, посвященное бракосочетанию Абылая и Айши.",
      inviteText2: "Разделите с нами нашу радость, подарите свою поддержку, а мы с радостью подарим вам частичку нашего счастья.",
      inviteText3: "Свадьба состоится 16 июля текущего года в г. Алматы, в ресторане Gulvar",
      inviteText4: "Узату состоится 2 июля текущего года в г. Актобе, в ресторане Diana Palace",
      inviteText5: "С уважением Аскар и Алуа Базарбаевы!",
      inviteText6: "С уважением Мирлан и Назира!",
      datesWedding: "Дата и время проведения",
      weddingDate: "16 июля 17:00",
      uzatuDate: "2 июля",
      weddingDateLabel: "Свадьба",
      uzatuDateLabel: "Узату",
      daysLeft: "Дней",
      hoursLeft: "Часов",
      minutesLeft: "Минут",
      secondsLeft: "Секунд",
      gallery: "Галерея",
      restaurantPlaceLabel: "Расположение ресторана (свадьба)",
      uzatuRestaurantPlaceLabel: "Расположение ресторана (узату)",
      restaurantNameLabel: "Название ресторана",
      restaurantName: "ресторанный комплекс \"Gulvar\"",
      restaurantAddressLabel: "Адрес",
      restaurantAddress: "Казыбек би, 43 (г. Алматы)",
      uzatuRestaurantName: "ресторан \"Diana Palace\"",
      uzatuRestaurantAddress: "Юго-запад 1, участок 663",
      tapToOpen2Gis: "Нажмите, что бы открыть 2ГИС",
      haveQuestions: "Остались вопросы?",
      writeMe: "Напишите мне (WhatsApp):",
      place :"Расположение",
      enter: "Вход",
      surname: "Фамилия",
      name: "Имя",
      validateError: "Попробуйте еще раз",
      enterButton: "Войти"
    },
    kz: {
      label: "Жазғы мейрам",
      dear: "Құрметті",
      and: "және",
      dearMale: "Қымбатты",
      dearFemale: "Қымбатты",
      inviteText1: "Сіздерді(Сізді) Абылай мен Айшаның шаңырақ көтеруіне арналған отбасылық мерекемізге шақырамыз.",
      inviteText2: "Біздің қуанышымызды бірге бөлісіңіз,қолдау көрсетсеңіз,біз Сізге өз бақытымыздың бір бөлігін сыйлаймыз.",
      inviteText3: "Той биылғы жылдың 16 шілдесінде Алматы қаласында, «Gulvar» мейрамханасында өтеді",
      inviteText4: "Ұзату той биылғы жылдың 2 шілдесінде Ақтөбе қаласында “Diana Palace” мейрамханасында өтеді",
      inviteText5: "Игі тілекпен Асқар және Алуа Базарбаевтар!",
      inviteText6: "Игі тілекпен Мирлан және Назира!",
      datesWedding: "Өтетін күні",
      weddingDate: "16 шілде 17:00",
      uzatuDate: "2 шілде",
      weddingDateLabel: "Той",
      uzatuDateLabel: "Ұзату",
      daysLeft: "Күн",
      hoursLeft: "Сағат",
      minutesLeft: "Минут",
      secondsLeft: "Секунд",
      gallery: "Галерея",
      restaurantPlaceLabel: "Ресторанның орналасуы(той)",
      uzatuRestaurantPlaceLabel: "Ресторанның орналасуы(ұзату)",
      restaurantNameLabel: "Ресторанның атауы",
      restaurantName: "ресторандық комплекс \"Gulvar\"",
      restaurantAddressLabel: "Адрес",
      restaurantAddress: "Казыбек би, 43 (г. Алматы)",
      uzatuRestaurantName: "ресторан \"Dina Palace\"",
      uzatuRestaurantAddress: "Юго-запад 1, участок 663",
      tapToOpen2Gis: "2ГИС-ті ашу үшін басыңыз",
      haveQuestions: "Сұрақтарыңыз болса",
      writeMe: "хабарласыңыз” (WhatsApp):",
      place :"Орналасуы",
      enter: "Кіру",
      surname: "Тегі",
      name: "Аты",
      validateError: "Тағы да қайталап көріңіз(орысша әріппен)",
      enterButton: "Кіру"
    }
  }
};
