module.exports=[
 {
  "id":0,
  "surname":"Базарбаев",
  "name":"Абылай",
  "patronymic":"Аскарович",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":1,
  "isYoung":true,
  "fullName":false
 },

 {
  "id":1,
  "surname":"Базарбаева",
  "name":"Аиша",
  "patronymic":"Мирлановна",
  "wedding":true,
  "uzatu":true,
  "sex":"W",
  "spouse":0,
  "isYoung":true,
  "fullName":false
 },

 {
  "id":2,
  "surname":"Базарбаев",
  "name":"Илияс",
  "patronymic":"Аскарович",
  "wedding":true,
  "uzatu":true,
  "sex":"M",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":100,
  "surname":"Коссиябек",
  "name":"Аслан",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":101,
  "surname":"Умирзаков",
  "name":"Даурен",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":102,
  "surname":"Сансызбай",
  "name":"Бауыржан",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":103,
  "surname":"Агатаеев",
  "name":"Асылжан",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":104,
  "surname":"Абдимуканкызы",
  "name":"Акерке",
  "wedding":true,
  "uzatu":false,
  "sex":"W",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":105,
  "surname":"Жараспай",
  "name":"Арслан",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":106,
  "surname":"Орынбасаров",
  "name":"Абай",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":107,
  "surname":"Абдрахманов",
  "name":"Руслан",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":109,
  "surname":"Дауталы",
  "name":"Максат",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":110,
  "isYoung":true,
  "fullName":false
 },

 {
  "id":110,
  "surname":"Гусмаулемова",
  "name":"Алуа",
  "wedding":true,
  "uzatu":false,
  "sex":"W",
  "spouse":109,
  "isYoung":true,
  "fullName":false
 },

 {
  "id":111,
  "surname":"Кусаинов",
  "name":"Темирлан",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":112,
  "isYoung":true,
  "fullName":false
 },

 {
  "id":112,
  "surname":"Лаюрова",
  "name":"Валентина",
  "wedding":true,
  "uzatu":false,
  "sex":"W",
  "spouse":111,
  "isYoung":true,
  "fullName":false
 },

 {
  "id":113,
  "surname":"Косанова",
  "name":"Алия",
  "wedding":true,
  "uzatu":false,
  "sex":"W",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":114,
  "surname":"Ыбраева",
  "name":"Аяулым",
  "wedding":true,
  "uzatu":false,
  "sex":"W",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":115,
  "surname":"Абдразак",
  "name":"Ерсин",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":116,
  "surname":"Мубараков",
  "name":"Нуржас",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":117,
  "surname":"Балгабай",
  "name":"Нурасыл",
  "wedding":true,
  "uzatu":true,
  "sex":"M",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":118,
  "surname":"Нуртуганулы",
  "name":"Нурсултан",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":119,
  "surname":"Аманжол",
  "name":"Асылбек",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":120,
  "surname":"Омаров",
  "name":"Даурен",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":121,
  "surname":"Амангельды",
  "name":"Данияр",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":122,
  "surname":"Кудайбергенов",
  "name":"Бекзат",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":123,
  "isYoung":true,
  "fullName":false
 },

 {
  "id":123,
  "surname":"Оразбекова",
  "name":"Сания",
  "wedding":true,
  "uzatu":false,
  "sex":"W",
  "spouse":122,
  "isYoung":true,
  "fullName":false
 },

 {
  "id":124,
  "surname":"Алдияров",
  "name":"Нуртлеу",
  "wedding":true,
  "uzatu":true,
  "sex":"M",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":125,
  "surname":"Акрам",
  "name":"Алишер",
  "wedding":true,
  "uzatu":true,
  "sex":"M",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":1261,
  "surname":"Кувандыкова",
  "name":"Жанна",
  "wedding":true,
  "uzatu":true,
  "sex":"W",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":126,
  "surname":"Каиргельдинов",
  "name":"Ахат",
  "wedding":true,
  "uzatu":true,
  "sex":"M",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":127,
  "surname":"Даутова",
  "name":"Дания",
  "wedding":true,
  "uzatu":false,
  "sex":"W",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":128,
  "surname":"Султанов",
  "name":"Сабит",
  "wedding":true,
  "uzatu":true,
  "sex":"M",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":129,
  "surname":"Мутахан",
  "name":"Ерасыл",
  "wedding":true,
  "uzatu":true,
  "sex":"M",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":130,
  "surname":"Райымбеккызы",
  "name":"Гульназ",
  "wedding":true,
  "uzatu":false,
  "sex":"W",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":131,
  "surname":"Темирханова",
  "name":"Махаббат",
  "wedding":true,
  "uzatu":false,
  "sex":"W",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":132,
  "surname":"Жанаев",
  "name":"Алишер",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":133,
  "isYoung":true,
  "fullName":false
 },

 {
  "id":133,
  "surname":"Жанаева",
  "name":"Алика",
  "wedding":true,
  "uzatu":false,
  "sex":"W",
  "spouse":132,
  "isYoung":true,
  "fullName":false
 },

 {
  "id":134,
  "surname":"Турдиев",
  "name":"Рустам",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":135,
  "isYoung":true,
  "fullName":false
 },

 {
  "id":135,
  "surname":"Турдиева",
  "name":"Асель",
  "wedding":true,
  "uzatu":false,
  "sex":"W",
  "spouse":134,
  "isYoung":true,
  "fullName":false
 },

 {
  "id":136,
  "surname":"Биржан",
  "name":"Азель",
  "wedding":true,
  "uzatu":false,
  "sex":"W",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":137,
  "surname":"Абубакирова",
  "name":"Айгерим",
  "wedding":true,
  "uzatu":false,
  "sex":"W",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":3,
  "surname":"Нургалиев",
  "name":"Айжарык",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":null,
  "isYoung":false,
  "fullName":true
 },

 {
  "id":4,
  "surname":"Нургалиева",
  "name":"Камажай",
  "wedding":true,
  "uzatu":true,
  "sex":"W",
  "spouse":5,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":5,
  "surname":"Нургалиев",
  "name":"Марат",
  "wedding":true,
  "uzatu":true,
  "sex":"M",
  "spouse":4,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":6,
  "surname":"Нургалиев",
  "name":"Бауыржан",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":7,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":7,
  "surname":"Нургалиева",
  "name":"Айкоркем",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":6,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":8,
  "surname":"Нургалиев",
  "name":"Азамат",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":9,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":9,
  "surname":"Нургалиева",
  "name":"Алмагул",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":8,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":10,
  "surname":"Нурыков",
  "name":"Жайык",
  "wedding":true,
  "uzatu":true,
  "sex":"M",
  "spouse":11,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":11,
  "surname":"Нурыкова",
  "name":"Карылга",
  "wedding":true,
  "uzatu":true,
  "sex":"W",
  "spouse":10,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":12,
  "surname":"Нурыков",
  "name":"Тилек",
  "wedding":true,
  "uzatu":true,
  "sex":"M",
  "spouse":13,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":13,
  "surname":"Нурыкова",
  "name":"Жазира",
  "wedding":true,
  "uzatu":true,
  "sex":"W",
  "spouse":12,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":14,
  "surname":"Нурыкова",
  "name":"Меруерт",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":null,
  "isYoung":false,
  "fullName":true
 },

 {
  "id":15,
  "surname":"Нурыков",
  "name":"Тимур",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":16,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":16,
  "surname":"Нурыкова",
  "name":"Гулнар",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":15,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":17,
  "surname":"Тумышев",
  "name":"Маденбай",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":18,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":18,
  "surname":"Тумышева",
  "name":"Несибели",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":17,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":19,
  "surname":"Тумышев",
  "name":"Нурлан",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":20,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":20,
  "surname":"Тумышева",
  "name":"Сандигуль",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":19,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":21,
  "surname":"Тумышева",
  "name":"Кымбат",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":null,
  "isYoung":false,
  "fullName":true
 },

 {
  "id":22,
  "surname":"Кенжебаев",
  "name":"Мухтар",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":null,
  "isYoung":false,
  "fullName":true
 },

 {
  "id":23,
  "surname":"Кенжебаев",
  "name":"Алпыс",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":24,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":24,
  "surname":"Кенжебаев",
  "name":"Базаргуль",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":23,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":25,
  "surname":"Кенжебаев",
  "name":"Амангали",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":26,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":26,
  "surname":"Кенжебаева",
  "name":"Тойлаш",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":25,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":27,
  "surname":"Кенжебаев",
  "name":"Елубай",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":null,
  "isYoung":false,
  "fullName":true
 },

 {
  "id":28,
  "surname":"Кызылбаев",
  "name":"Бакытжан",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":29,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":29,
  "surname":"Кызылбаева",
  "name":"Зиба",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":28,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":30,
  "surname":"Кызылбаева",
  "name":"Рая",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":null,
  "isYoung":false,
  "fullName":true
 },

 {
  "id":31,
  "surname":"Хайруллин",
  "name":"Султан",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":32,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":32,
  "surname":"Хайруллина",
  "name":"Клара",
  "wedding":true,
  "uzatu":true,
  "sex":"W",
  "spouse":31,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":33,
  "surname":"Хайруллина",
  "name":"Куляш",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":34,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":34,
  "surname":"Хайруллин",
  "name":"Болат",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":33,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":3411,
  "surname":"Хайруллин",
  "name":"Серик",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":35,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":35,
  "surname":"Хайруллина",
  "name":"Улболсын",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":3411,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":36,
  "surname":"Косжанов",
  "name":"Арыстанбек",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":37,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":37,
  "surname":"Косжанова",
  "name":"Айнаш",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":36,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":38,
  "surname":"Косжанов",
  "name":"Аслан",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":null,
  "isYoung":false,
  "fullName":true
 },

 {
  "id":39,
  "surname":"Орынбаева",
  "name":"Римма",
  "wedding":true,
  "uzatu":true,
  "sex":"W",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":40,
  "surname":"Урынбаева",
  "name":"Аида",
  "wedding":true,
  "uzatu":true,
  "sex":"W",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":41,
  "surname":"Нуракын",
  "name":"Асия",
  "wedding":true,
  "uzatu":true,
  "sex":"W",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":42,
  "surname":"Нуракын",
  "name":"Амина",
  "wedding":true,
  "uzatu":true,
  "sex":"W",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":43,
  "surname":"Тулебаева",
  "name":"Айгуль",
  "wedding":true,
  "uzatu":true,
  "sex":"W",
  "spouse":44,
  "isYoung":true,
  "fullName":false
 },

 {
  "id":44,
  "surname":"Урынбаев",
  "name":"Альбек",
  "wedding":true,
  "uzatu":true,
  "sex":"M",
  "spouse":43,
  "isYoung":true,
  "fullName":false
 },

 {
  "id":45,
  "surname":"Урынбаева",
  "name":"Айнель",
  "wedding":true,
  "uzatu":true,
  "sex":"W",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":46,
  "surname":"Орынбаев",
  "name":"Торемурат",
  "wedding":true,
  "uzatu":true,
  "sex":"M",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":47,
  "surname":"Тулебаева",
  "name":"Мадина",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":48,
  "surname":"Абдуллин",
  "name":"Бердыкул",
  "wedding":true,
  "uzatu":true,
  "sex":"M",
  "spouse":49,
  "isYoung":true,
  "fullName":false
 },

 {
  "id":49,
  "surname":"Каратаева",
  "name":"Шуга",
  "wedding":true,
  "uzatu":true,
  "sex":"W",
  "spouse":48,
  "isYoung":true,
  "fullName":false
 },

 {
  "id":50,
  "surname":"Абдуллин",
  "name":"Жандос",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":51,
  "isYoung":true,
  "fullName":false
 },

 {
  "id":51,
  "surname":"Абдуллина",
  "name":"Асем",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":50,
  "isYoung":true,
  "fullName":false
 },

 {
  "id":52,
  "surname":"Абдуллин",
  "name":"Жамболат",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":53,
  "isYoung":true,
  "fullName":false
 },

 {
  "id":53,
  "surname":"Абдуллина",
  "name":"Айжан",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":52,
  "isYoung":true,
  "fullName":false
 },

 {
  "id":54,
  "surname":"Абдуллин",
  "name":"Еламан",
  "wedding":true,
  "uzatu":true,
  "sex":"M",
  "spouse":55,
  "isYoung":true,
  "fullName":false
 },

 {
  "id":55,
  "surname":"Абдуллина",
  "name":"Алия",
  "wedding":true,
  "uzatu":true,
  "sex":"W",
  "spouse":54,
  "isYoung":true,
  "fullName":false
 },

 {
  "id":56,
  "surname":"Жалгасбаев",
  "name":"Бокенбай",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":57,
  "isYoung":true,
  "fullName":false
 },

 {
  "id":57,
  "surname":"Жалгасбаева",
  "name":"Айжан",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":56,
  "isYoung":true,
  "fullName":false
 },

 {
  "id":58,
  "surname":"Жалгасбаев",
  "name":"Думан",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":59,
  "surname":"Атагалиев",
  "name":"Каныш",
  "wedding":true,
  "uzatu":true,
  "sex":"M",
  "spouse":60,
  "isYoung":true,
  "fullName":false
 },

 {
  "id":60,
  "surname":"Атагалиева",
  "name":"Жаныл",
  "wedding":true,
  "uzatu":true,
  "sex":"W",
  "spouse":59,
  "isYoung":true,
  "fullName":false
 },

 {
  "id":61,
  "surname":"Абдуллин",
  "name":"Бердигали",
  "wedding":true,
  "uzatu":true,
  "sex":"M",
  "spouse":62,
  "isYoung":true,
  "fullName":false
 },

 {
  "id":62,
  "surname":"Абдуллина",
  "name":"Баршагул",
  "wedding":true,
  "uzatu":true,
  "sex":"W",
  "spouse":61,
  "isYoung":true,
  "fullName":false
 },

 {
  "id":63,
  "surname":"Абдуллин",
  "name":"Нуржан",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":64,
  "isYoung":true,
  "fullName":false
 },

 {
  "id":64,
  "surname":"Абдуллина",
  "name":"Мадина",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":63,
  "isYoung":true,
  "fullName":false
 },

 {
  "id":65,
  "surname":"Абдуллин",
  "name":"Даурен",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":66,
  "isYoung":true,
  "fullName":false
 },

 {
  "id":66,
  "surname":"Абдуллина",
  "name":"Нурлыгул",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":67,
  "isYoung":true,
  "fullName":false
 },

 {
  "id":67,
  "surname":"Абдуллин",
  "name":"Аксункар",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":68,
  "isYoung":true,
  "fullName":false
 },

 {
  "id":68,
  "surname":"Абдуллина",
  "name":"Аружан",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":69,
  "isYoung":true,
  "fullName":false
 },

 {
  "id":69,
  "surname":"Абдуллинf",
  "name":"Алтынгул",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":70,
  "surname":"Бисен",
  "name":"Махаббат",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":71,
  "surname":"Абдуллин",
  "name":"Косым",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":72,
  "isYoung":true,
  "fullName":false
 },

 {
  "id":72,
  "surname":"Абдуллина",
  "name":"Жанар",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":71,
  "isYoung":true,
  "fullName":false
 },

 {
  "id":73,
  "surname":"Курманова",
  "name":"Багдар",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":74,
  "isYoung":true,
  "fullName":false
 },

 {
  "id":74,
  "surname":"Курманов",
  "name":"Ерхан",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":73,
  "isYoung":true,
  "fullName":false
 },

 {
  "id":75,
  "surname":"Орынбаева",
  "name":"Айгуль",
  "wedding":true,
  "uzatu":true,
  "sex":"W",
  "spouse":76,
  "isYoung":true,
  "fullName":false
 },

 {
  "id":76,
  "surname":"Изтлеуов",
  "name":"Сакен",
  "wedding":true,
  "uzatu":true,
  "sex":"M",
  "spouse":75,
  "isYoung":true,
  "fullName":false
 },

 {
  "id":77,
  "surname":"Байдуллина",
  "name":"Нургуль",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":null,
  "isYoung":false,
  "fullName":true
 },

 {
  "id":78,
  "surname":"Аймукатов",
  "name":"Аскар",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":79,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":79,
  "surname":"Аймыкатова",
  "name":"Айымхан",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":78,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":80,
  "surname":"Жалгасбаев",
  "name":"Байжума",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":81,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":81,
  "surname":"Жалгасбаева",
  "name":"Сулушаш",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":80,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":82,
  "surname":"Жалгасбаев",
  "name":"Кайрат",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":83,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":83,
  "surname":"Жалгасбаева",
  "name":"Жансая",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":82,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":84,
  "surname":"Жалгасбаев",
  "name":"Кайыржан",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":85,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":85,
  "surname":"Жалгасбаева",
  "name":"Гулмира",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":84,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":86,
  "surname":"Жалгасбаев",
  "name":"Жайгали",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":87,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":87,
  "surname":"Жалгасбаева",
  "name":"Гулжахан",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":86,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":88,
  "surname":"Жалгасбаев",
  "name":"Байгали",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":89,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":89,
  "surname":"Жалгасбаева",
  "name":"Сакен",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":88,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":90,
  "surname":"Жалгасбаев",
  "name":"Бауыржан",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":91,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":91,
  "surname":"Жалгасбаева",
  "name":"Роза",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":90,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":92,
  "surname":"Тулебаев",
  "name":"Нурбек",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":93,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":93,
  "surname":"Тулебаева",
  "name":"Гулзира",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":92,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":94,
  "surname":"Кустаулетов",
  "name":"Миндихан",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":93,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":95,
  "surname":"Кустаулетова",
  "name":"Гулмира",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":94,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":96,
  "surname":"Нургабылов",
  "name":"Дархан",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":97,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":97,
  "surname":"Нургабылова",
  "name":"Алтынгуль",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":96,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":98,
  "surname":"Отаров",
  "name":"Бекжан",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":99,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":99,
  "surname":"Отарова",
  "name":"Гулдаурен",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":98,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":200,
  "surname":"Кантарбаев",
  "name":"Артур",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":201,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":201,
  "surname":"Кантарбаева",
  "name":"Айгуль",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":200,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":202,
  "surname":"Бактыгереев",
  "name":"Алтынбек",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":203,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":203,
  "surname":"Бактыгереева",
  "name":"Мадина",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":202,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":204,
  "surname":"Ихсанов",
  "name":"Талгат",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":205,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":205,
  "surname":"Ихсанова",
  "name":"Гулсим",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":204,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":206,
  "surname":"Нуршина",
  "name":"Жайна",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":null,
  "isYoung":false,
  "fullName":true
 },

 {
  "id":207,
  "surname":"Досмайлов",
  "name":"Сеит",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":208,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":208,
  "surname":"Досмайлова",
  "name":"Ляззат",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":207,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":209,
  "surname":"Кумаргалиев",
  "name":"Зинур",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":210,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":210,
  "surname":"Кумаргалиева",
  "name":"Зияш",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":209,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":211,
  "surname":"Саулебаев",
  "name":"Турлан",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":212,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":212,
  "surname":"Саулебаева",
  "name":"Роза",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":211,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":213,
  "surname":"Конакбаев",
  "name":"Бериккали",
  "wedding":false,
  "uzatu":true,
  "sex":"M ",
  "spouse":214,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":214,
  "surname":"Конакбаева",
  "name":"Маржан",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":213,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":215,
  "surname":"Елдесбаев",
  "name":"Кенжетай",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":216,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":216,
  "surname":"Кенжетаева",
  "name":"Гулнар",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":215,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":217,
  "surname":"Жолдыбаева",
  "name":"Гулнар",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":null,
  "isYoung":false,
  "fullName":true
 },

 {
  "id":218,
  "surname":"Каласова",
  "name":"Айсауле",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":null,
  "isYoung":false,
  "fullName":true
 },

 {
  "id":219,
  "surname":"Балмагамбетова",
  "name":"Нургуль",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":null,
  "isYoung":false,
  "fullName":true
 },

 {
  "id":220,
  "surname":"Орынбасарова",
  "name":"Нургуль",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":null,
  "isYoung":false,
  "fullName":true
 },

 {
  "id":221,
  "surname":"Абдрахманова",
  "name":"Анаргуль",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":null,
  "isYoung":false,
  "fullName":true
 },

 {
  "id":222,
  "surname":"Карасаева",
  "name":"Рита",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":null,
  "isYoung":false,
  "fullName":true
 },

 {
  "id":223,
  "surname":"Карагулова",
  "name":"Рита",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":null,
  "isYoung":false,
  "fullName":true
 },

 {
  "id":224,
  "surname":"Утегенова",
  "name":"Райгуль",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":null,
  "isYoung":false,
  "fullName":true
 },

 {
  "id":225,
  "surname":"Букенов",
  "name":"Арман",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":null,
  "isYoung":false,
  "fullName":true
 },

 {
  "id":226,
  "surname":"Муратов",
  "name":"Талгат",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":null,
  "isYoung":false,
  "fullName":true
 },

 {
  "id":227,
  "surname":"Рускулова",
  "name":"Ляззат",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":null,
  "isYoung":false,
  "fullName":true
 },

 {
  "id":228,
  "surname":"Отарова",
  "name":"Айжан",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":null,
  "isYoung":false,
  "fullName":true
 },

 {
  "id":229,
  "surname":"Сисенгалиева",
  "name":"Думан",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":null,
  "isYoung":false,
  "fullName":true
 },

 {
  "id":230,
  "surname":"Еспусинова",
  "name":"Жанаргуль",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":null,
  "isYoung":false,
  "fullName":true
 },

 {
  "id":231,
  "surname":"Гетман",
  "name":"Лилия",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":null,
  "isYoung":false,
  "fullName":true
 },

 {
  "id":232,
  "surname":"Есполова",
  "name":"Жанна",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":null,
  "isYoung":false,
  "fullName":true
 },

 {
  "id":233,
  "surname":"Алпысбаева",
  "name":"Сания",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":null,
  "isYoung":false,
  "fullName":true
 },

 {
  "id":234,
  "surname":"Габбасова",
  "name":"Райса",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":null,
  "isYoung":false,
  "fullName":true
 },

 {
  "id":235,
  "surname":"Аймуканова",
  "name":"Раушан",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":null,
  "isYoung":false,
  "fullName":true
 },

 {
  "id":236,
  "surname":"Байдуллин",
  "name":"Досым",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":237,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":237,
  "surname":"Байдуллина",
  "name":"Нургуль",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":236,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":238,
  "surname":"Есетов",
  "name":"Айдарбек",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":239,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":239,
  "surname":"Есетова",
  "name":"Гулнар",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":238,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":240,
  "surname":"Абдуллина",
  "name":"Назира",
  "wedding":true,
  "uzatu":true,
  "sex":"W",
  "spouse":241,
  "isYoung":true,
  "fullName":false
 },

 {
  "id":241,
  "surname":"Орынбай",
  "name":"Мирлан",
  "wedding":true,
  "uzatu":true,
  "sex":"M",
  "spouse":240,
  "isYoung":true,
  "fullName":false
 },

 {
  "id":242,
  "surname":"Матжан",
  "name":"Маргулан",
  "wedding":true,
  "uzatu":true,
  "sex":"M",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":243,
  "surname":"Матжанов",
  "name":"Тамырлан",
  "wedding":true,
  "uzatu":true,
  "sex":"M",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":244,
  "surname":"Орынбаев",
  "name":"Нурлан",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":300,
  "surname":"Ташим",
  "name":"Данияр",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":301,
  "surname":"Сайлаубек",
  "name":"Мурат",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":302,
  "surname":"Максутова",
  "name":"Акмарал",
  "wedding":true,
  "uzatu":false,
  "sex":"W",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":303,
  "surname":"Федоров",
  "name":"Вячеслав",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":304,
  "surname":"Усаев",
  "name":"Ерик",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":305,
  "surname":"Айбасов",
  "name":"Сансызбай",
   "patronymic":"Кусаинович",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":306,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":306,
  "surname":"Базарбаева",
  "name":"Лязат",
  "wedding":true,
  "uzatu":false,
  "sex":"W",
  "spouse":305,
  "isYoung":true,
  "fullName":false
 },

 {
  "id":307,
  "surname":"Базарбаева",
  "name":"Лариса",
  "wedding":true,
  "uzatu":false,
  "sex":"W",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":308,
  "surname":"Кульбаева",
  "name":"Карлыгаш",
  "wedding":true,
  "uzatu":false,
  "sex":"W",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":309,
  "surname":"Идрисова",
  "name":"Данара",
  "wedding":true,
  "uzatu":false,
  "sex":"W",
  "spouse":310,
  "isYoung":true,
  "fullName":false
 },

 {
  "id":310,
  "surname":"Стамшалов",
  "name":"Азамат",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":309,
  "isYoung":true,
  "fullName":false
 },

 {
  "id":311,
  "surname":"Кульбаев",
  "name":"Даулет",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":312,
  "surname":"Касымова",
  "name":"Мариям",
  "wedding":true,
  "uzatu":false,
  "sex":"W",
  "spouse":313,
  "isYoung":true,
  "fullName":false
 },

 {
  "id":313,
  "surname":"Касымов",
  "name":"Ихтиер",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":312,
  "isYoung":true,
  "fullName":false
 },

 {
  "id":314,
  "surname":"Кульбаева",
  "name":"Айгерим",
  "wedding":true,
  "uzatu":false,
  "sex":"W",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":315,
  "surname":"Базарбаева",
  "name":"Кумис",
  "wedding":true,
  "uzatu":false,
  "sex":"W",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":316,
  "surname":"Базарбаев",
  "name":"Ернар",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":317,
  "isYoung":true,
  "fullName":false
 },

 {
  "id":317,
  "surname":"Джумалиева",
  "name":"Дания",
  "wedding":true,
  "uzatu":false,
  "sex":"W",
  "spouse":316,
  "isYoung":true,
  "fullName":false
 },

 {
  "id":318,
  "surname":"Чикало",
  "name":"Дильда",
  "wedding":true,
  "uzatu":false,
  "sex":"W",
  "spouse":319,
  "isYoung":true,
  "fullName":false
 },

 {
  "id":319,
  "surname":"Чикало",
  "name":"Иван",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":318,
  "isYoung":true,
  "fullName":false
 },

 {
  "id":320,
  "surname":"Нургаликов",
  "name":"Берик",
   "patronymic":"Аға",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":321,
  "isYoung":false,
  "fullName":true
 },

 {
  "id":321,
  "surname":"Нургаликова",
  "name":"Зайтуна",
   "patronymic":"Жеңгей",
  "wedding":true,
  "uzatu":false,
  "sex":"W",
  "spouse":320,
  "isYoung":false,
  "fullName":true
 },

 {
  "id":322,
  "surname":"Нургаликов",
  "name":"Серик",
   "patronymic":"Аға",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":323,
  "isYoung":false,
  "fullName":true
 },

 {
  "id":323,
  "surname":"Нургаликова",
  "name":"Рыс",
   "patronymic":"Жеңгей",
  "wedding":true,
  "uzatu":false,
  "sex":"W",
  "spouse":322,
  "isYoung":false,
  "fullName":true
 },

 {
  "id":324,
  "surname":"Кангужина",
  "name":"Салтанат",
   "patronymic":"Жаксыгалиевна",
  "wedding":true,
  "uzatu":false,
  "sex":"W",
  "spouse":null,
  "isYoung":false,
  "fullName":true
 },

 {
  "id":325,
  "surname":"Букенов",
  "name":"Болат",
   "patronymic":"Салтаевич",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":326,
  "isYoung":false,
  "fullName":true
 },

 {
  "id":326,
  "surname":"Букенова",
  "name":"Раушан",
  "wedding":true,
  "uzatu":false,
  "sex":"W",
  "spouse":325,
  "isYoung":false,
  "fullName":true
 },

 {
  "id":327,
  "surname":"Стамшалова",
  "name":"Дарига",
  "wedding":true,
  "uzatu":false,
  "sex":"W",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":328,
  "surname":"Стамшалов",
  "name":"Ильяс",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":329,
  "surname":"Касымов",
  "name":"Ансар",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":330,
  "surname":"Касымова",
  "name":"Арина",
  "wedding":true,
  "uzatu":false,
  "sex":"W",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":331,
  "surname":"Базарбаев",
  "name":"Алим",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":332,
  "surname":"Абильмажинова",
  "name":"Дана",
  "wedding":true,
  "uzatu":false,
  "sex":"W",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":333,
  "surname":"Абильмажинов",
  "name":"Ертай",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":334,
  "isYoung":true,
  "fullName":false
 },

 {
  "id":334,
  "surname":"Абильмажинова",
  "name":"Айгуль",
  "wedding":true,
  "uzatu":false,
  "sex":"W",
  "spouse":333,
  "isYoung":true,
  "fullName":false
 },

 {
  "id":335,
  "surname":"Абильмажинов",
  "name":"Айкын",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":336,
  "isYoung":true,
  "fullName":false
 },

 {
  "id":336,
  "surname":"Абильмажинова",
  "name":"Ляйля",
  "wedding":true,
  "uzatu":false,
  "sex":"W",
  "spouse":335,
  "isYoung":true,
  "fullName":false
 },

 {
  "id":337,
  "surname":"Шакиров",
  "name":"Чингиз",
  "wedding":true,
  "uzatu":true,
  "sex":"M",
  "spouse":338,
  "isYoung":true,
  "fullName":false
 },

 {
  "id":338,
  "surname":"Шакирова",
  "name":"Ляззат",
  "wedding":true,
  "uzatu":false,
  "sex":"W",
  "spouse":337,
  "isYoung":true,
  "fullName":false
 },

 {
  "id":339,
  "surname":"Шакиров",
  "name":"Санжар",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":340,
  "surname":"Алдабергенов",
  "name":"Ертас",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":null,
  "isYoung": false,
  "fullName":true
 },

 {
  "id":341,
  "surname":"Муканова",
  "name":"Роза",
  "wedding":true,
  "uzatu":false,
  "sex":"W",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":342,
  "surname":"Актай",
  "name":"Адиль",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":343,
  "surname":"Абильмажинова",
  "name":"Дания",
  "wedding":true,
  "uzatu":false,
  "sex":"W",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":344,
  "surname":"Базарбаев",
  "name":"Аскар",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":345,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":345,
  "surname":"Базарбаева",
  "name":"Алуа",
  "wedding":true,
  "uzatu":false,
  "sex":"W",
  "spouse":344,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":245,
  "surname":"Сыздыков",
  "name":"Елкаир",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":246,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":246,
  "surname":"Сыздыкова",
  "name":"Батиза",
  "wedding":true,
  "uzatu":false,
  "sex":"W",
  "spouse":245,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":247,
  "surname":"Абдиказимов",
  "name":"Кабдулкарим",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":248,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":248,
  "surname":"Жунусбекова",
  "name":"Гульнара",
  "wedding":true,
  "uzatu":false,
  "sex":"W",
  "spouse":247,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":249,
  "surname":"Нургалиев",
  "name":"Нурлан",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":1249,
  "isYoung":false,
  "fullName":false
 },

  {
    "id":1249,
    "surname":"Нургалиева",
    "name":"Инара",
    "wedding":true,
    "uzatu":false,
    "sex":"W",
    "spouse":249,
    "isYoung":false,
    "fullName":false
  },

 {
  "id":250,
  "surname":"Усов",
  "name":"Дмитрий",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":251,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":251,
  "surname":"Усова",
  "name":"Яна",
  "wedding":true,
  "uzatu":false,
  "sex":"W",
  "spouse":250,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":252,
  "surname":"Арстанов",
  "name":"Адильхан",
   "patronymic":"Арстанович",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":253,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":253,
  "surname":"Сапарова",
  "name":"Сулушаш",
  "wedding":true,
  "uzatu":false,
  "sex":"W",
  "spouse":252,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":254,
  "surname":"Бекбанова",
  "name":"Жанар",
   "patronymic":"Рустемовна",
  "wedding":true,
  "uzatu":false,
  "sex":"W",
  "spouse":null,
  "isYoung":false,
  "fullName":true
 },

 {
  "id":255,
  "surname":"Ахметов",
  "name":"Куат",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":null,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":256,
  "surname":"Игенбаев",
  "name":"Рауан",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":257,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":257,
  "surname":"Игенбаева",
  "name":"Акерке",
  "wedding":true,
  "uzatu":false,
  "sex":"W",
  "spouse":256,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":258,
  "surname":"Сейфулин",
  "name":"Данияр",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":null,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":259,
  "surname":"Сыздыков",
  "name":"Рустем",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":260,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":260,
  "surname":"Сыздыкова",
  "name":"Акбота",
  "wedding":true,
  "uzatu":false,
  "sex":"W",
  "spouse":259,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":261,
  "surname":"Халилин",
  "name":"Ерден",
   "patronymic":"Балтабаевич",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":262,
  "isYoung":false,
  "fullName":true
 },

 {
  "id":262,
  "surname":"Халилина",
  "name":"Гульжанат",
  "wedding":true,
  "uzatu":false,
  "sex":"W",
  "spouse":261,
  "isYoung":false,
  "fullName":true
 },

 {
  "id":263,
  "surname":"Ускенов",
  "name":"Канат",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":264,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":264,
  "surname":"Ускенова",
  "name":"Алмагуль",
  "wedding":true,
  "uzatu":false,
  "sex":"W",
  "spouse":263,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":265,
  "surname":"Шаймарданов",
  "name":"Ербол",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":266,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":266,
  "surname":"Шаймарданова",
  "name":"Айгуль",
  "wedding":true,
  "uzatu":false,
  "sex":"W",
  "spouse":265,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":267,
  "surname":"Кожахметов",
  "name":"Арман",
   "patronymic":"Тулешевич",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":268,
  "isYoung":false,
  "fullName":true
 },

 {
  "id":268,
  "surname":"Кожахметова",
  "name":"Тогжан",
  "wedding":true,
  "uzatu":false,
  "sex":"W",
  "spouse":267,
  "isYoung":false,
  "fullName":true
 },

 {
  "id":269,
  "surname":"Есентаев",
  "name":"Тастанбек",
   "patronymic":"Кутжанович",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":270,
  "isYoung":false,
  "fullName":true
 },

 {
  "id":270,
  "surname":"Есентаева",
  "name":"Зольта",
  "wedding":true,
  "uzatu":false,
  "sex":"W",
  "spouse":269,
  "isYoung":false,
  "fullName":true
 },

 {
  "id":271,
  "surname":"Жакенов",
  "name":"Серикжан",
   "patronymic":"Амиржанович",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":272,
  "isYoung":false,
  "fullName":true
 },

 {
  "id":272,
  "surname":"Жакенова",
  "name":"Куляш",
  "wedding":true,
  "uzatu":false,
  "sex":"W",
  "spouse":271,
  "isYoung":false,
  "fullName":true
 },

 {
  "id":273,
  "surname":"Омаров",
  "name":"Нариман",
   "patronymic":"Казиевич",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":274,
  "isYoung":false,
  "fullName":true
 },

 {
  "id":274,
  "surname":"Омарова",
  "name":"Гульшара",
  "wedding":true,
  "uzatu":false,
  "sex":"W",
  "spouse":273,
  "isYoung":false,
  "fullName":true
 },

 {
  "id":275,
  "surname":"Кушумбаев",
  "name":"Серикжан",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":276,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":276,
  "surname":"Кушумбаева",
  "name":"Нургуль",
  "wedding":true,
  "uzatu":false,
  "sex":"W",
  "spouse":275,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":277,
  "surname":"Куттыбай",
  "name":"Мирас",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":278,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":278,
  "surname":"Куттыбай",
  "name":"Гульмира",
  "wedding":true,
  "uzatu":false,
  "sex":"W",
  "spouse":277,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":279,
  "surname":"Калиева",
  "name":"Гульсара",
  "wedding":true,
  "uzatu":false,
  "sex":"W",
  "spouse":null,
  "isYoung":false,
  "fullName":true
 },

 {
  "id":280,
  "surname":"Мамбетова",
  "name":"Айша",
  "wedding":true,
  "uzatu":false,
  "sex":"W",
  "spouse":null,
  "isYoung":false,
  "fullName":true
 },

 {
  "id":281,
  "surname":"Мамбетов",
  "name":"Мурат",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":282,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":282,
  "surname":"Мамбетова",
  "name":"Лейла",
  "wedding":true,
  "uzatu":false,
  "sex":"W",
  "spouse":281,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":283,
  "surname":"Казанцев",
  "name":"Павел",
   "patronymic":"Олегович",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":1283,
  "isYoung":false,
  "fullName":true
 },

  {
    "id":1283,
    "surname":"Казанцева",
    "name":"Татьяна",
    "patronymic":"Михайловна",
    "wedding":true,
    "uzatu":false,
    "sex":"W",
    "spouse":283,
    "isYoung":false,
    "fullName":true
  },

 {
  "id":284,
  "surname":"Кожамкулов",
  "name":"Толеген",
   "patronymic":"Абдысагиевич",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":285,
  "isYoung":false,
  "fullName":true
 },

 {
  "id":285,
  "surname":"Исимбаева",
  "name":"Гульмира",
   "patronymic":"Истайбековна",
  "wedding":true,
  "uzatu":false,
  "sex":"W",
  "spouse":284,
  "isYoung":false,
  "fullName":true
 },

 {
  "id":286,
  "surname":"Абдысагин",
  "name":"Рахат-Би",
   "patronymic":"Толегенулы",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":null,
  "isYoung":false,
  "fullName":true
 },

 {
  "id":287,
  "surname":"Имангалиев",
  "name":"Есенгазы",
   "patronymic":"Нуртолеуович",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":1287,
  "isYoung":false,
  "fullName":true
 },

 {
  "id":1287,
  "surname":"Имангалиевв",
  "name":"Айша",
   "patronymic":"Аскеровна",
  "wedding":true,
  "uzatu":false,
  "sex":"W",
  "spouse":287,
  "isYoung":false,
  "fullName":true
 },

 {
  "id":288,
  "surname":"Тушаков",
  "name":"Марат",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":289,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":289,
  "surname":"Тушакова",
  "name":"Жулдыз",
  "wedding":true,
  "uzatu":false,
  "sex":"W",
  "spouse":288,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":290,
  "surname":"Нигматулин",
  "name":"Аргын",
   "patronymic":"Зайруллаевич",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":291,
  "isYoung":false,
  "fullName":true
 },

 {
  "id":291,
  "surname":"Нигматулина",
  "name":"Найля",
  "wedding":true,
  "uzatu":false,
  "sex":"W",
  "spouse":290,
  "isYoung":false,
  "fullName":true
 },

 {
  "id":292,
  "surname":"Кабидолла",
  "name":"Диана",
  "wedding":true,
  "uzatu":true,
  "sex":"W",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":293,
  "surname":"Кайролла",
  "name":"Айдын",
  "wedding":true,
  "uzatu":true,
  "sex":"M",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":294,
  "surname":"Кали",
  "name":"Чингиз",
  "wedding":true,
  "uzatu":true,
  "sex":"M",
  "spouse":null,
  "isYoung":true,
  "fullName":true
 },

 {
  "id":500,
  "surname":"Улжабаева",
  "name":"Светлана",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":null,
  "isYoung":false,
  "fullName":true
 },

 {
  "id":501,
  "surname":"Есенгалиев",
  "name":"Асылбек",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":502,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":502,
  "surname":"Есенгалиева",
  "name":"Жайгул",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":501,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":503,
  "surname":"Карабала",
  "name":"Файзолла",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":504,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":504,
  "surname":"Карабалла",
  "name":"Нургул",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":503,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":505,
  "surname":"Жалгасбаева",
  "name":"Айгул",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":null,
  "isYoung":false,
  "fullName":true
 },

 {
  "id":506,
  "surname":"Жалгасбаева",
  "name":"Назай",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":null,
  "isYoung":false,
  "fullName":true
 },

 {
  "id":507,
  "surname":"Жасуланов",
  "name":"Тимур",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":508,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":508,
  "surname":"Жасуланова",
  "name":"Гулнар",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":507,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":509,
  "surname":"Косдаулетов",
  "name":"Мендихан",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":510,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":510,
  "surname":"Косдаулетова",
  "name":"Гулмира",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":509,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":511,
  "surname":"Каракеев",
  "name":"Саттигул",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":512,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":512,
  "surname":"Каракеева",
  "name":"Жаркынай",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":511,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":513,
  "surname":"Мухамбетов",
  "name":"Руслан",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":514,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":514,
  "surname":"Мухамбетова",
  "name":"Айсауле",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":513,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":515,
  "surname":"Мухамбетова",
  "name":"Макфуза",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":null,
  "isYoung":false,
  "fullName":true
 },

 {
  "id":516,
  "surname":"Мухамбетова",
  "name":"Марфуга",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":517,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":518,
  "surname":"Мухамбетов",
  "name":"Жангелди",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":null,
  "isYoung":false,
  "fullName":true
 },

 {
  "id":519,
  "surname":"Мухамбетов",
  "name":"Сарсен",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":520,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":520,
  "surname":"Мухамбетова",
  "name":"Маржан",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":519,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":521,
  "surname":"Мухамбетов",
  "name":"Дуйсен",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":522,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":522,
  "surname":"Мухамбетова",
  "name":"Дария",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":521,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":523,
  "surname":"Мухамбетов",
  "name":"Жексен",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":524,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":524,
  "surname":"Мухамбетова",
  "name":"Жанна",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":525,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":525,
  "surname":"Мухамбетов",
  "name":"Елдар",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":526,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":526,
  "surname":"Мухамбетова",
  "name":"Айжан",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":525,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":527,
  "surname":"Алпысбай",
  "name":"Нурлан",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":528,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":528,
  "surname":"Алпысбай",
  "name":"Айман",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":527,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":529,
  "surname":"Отаргалиева",
  "name":"Назипа",
  "wedding":true,
  "uzatu":false,
  "sex":"W",
  "spouse":null,
  "isYoung":false,
  "fullName":true
 },

 {
  "id":530,
  "surname":"Хайролла",
  "name":"Аршат",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":531,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":531,
  "surname":"Хайролла",
  "name":"Сезим",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":530,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":532,
  "surname":"Хайролла",
  "name":"Нұрзат",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":533,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":533,
  "surname":"Хайролла",
  "name":"Маржан",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":532,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":534,
  "surname":"Молдашев",
  "name":"Болат",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":535,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":535,
  "surname":"Молдашева",
  "name":"Эльвира",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":534,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":536,
  "surname":"Пштаев",
  "name":"Асхат",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":537,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":537,
  "surname":"Пштаева",
  "name":"Сажида",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":536,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":538,
  "surname":"Валиев",
  "name":"Сагидолла",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":539,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":539,
  "surname":"Валиева",
  "name":"Дәмели",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":538,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":540,
  "surname":"Займолдин",
  "name":"Сакен",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":541,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":541,
  "surname":"Займолдина",
  "name":"Анар",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":540,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":542,
  "surname":"Тумышев",
  "name":"Ерлан",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":543,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":543,
  "surname":"Тумышева",
  "name":"Аксамал",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":542,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":544,
  "surname":"Аймукатов",
  "name":"Аскар",
  "wedding":false,
  "uzatu":true,
  "sex":"M",
  "spouse":545,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":545,
  "surname":"Аймукатова",
  "name":"Айымхан",
  "wedding":false,
  "uzatu":true,
  "sex":"W",
  "spouse":544,
  "isYoung":false,
  "fullName":false
 },

 {
  "id":546,
  "surname":"Нигматулин",
  "name":"Нурлан",
   "patronymic": "Зайруллаевич",
  "wedding":true,
  "uzatu":false,
  "sex":"M",
  "spouse":547,
  "isYoung":false,
  "fullName":true
 },

 {
  "id":547,
  "surname":"Баймурзаева",
  "name":"Венера",
   "patronymic": "Хамитовна",
  "wedding":true,
  "uzatu":false,
  "sex":"W",
  "spouse":546,
  "isYoung":false,
  "fullName":true
 },

  {
    "id":548,
    "surname":"Нигматулин",
    "name":"Ерлан",
    "patronymic": "Зайруллаевич",
    "wedding":true,
    "uzatu":false,
    "sex":"M",
    "spouse":549,
    "isYoung":false,
    "fullName":true
  },

  {
    "id":549,
    "surname":"Серикбаева",
    "name":"Бахыт",
    "patronymic": "Кайирбековна",
    "wedding":true,
    "uzatu":false,
    "sex":"W",
    "spouse":548,
    "isYoung":false,
    "fullName":true
  },

  {
    "id":550,
    "surname":"Аманжолова",
    "name":"Зауреш",
    "patronymic": "Джумалиевна",
    "wedding":true,
    "uzatu":false,
    "sex":"W",
    "spouse":1550,
    "isYoung":false,
    "fullName":true
  },

  {
    "id":1550,
    "surname":"Аманжолов",
    "name":"Адиль",
    "patronymic": "Ахметович",
    "wedding":true,
    "uzatu":false,
    "sex":"M",
    "spouse":550,
    "isYoung":false,
    "fullName":true
  },

  {
    "id":551,
    "surname":"Нуркина",
    "name":"Айгуль",
    "patronymic": "Кабдушевна",
    "wedding":true,
    "uzatu":false,
    "sex":"W",
    "spouse":552,
    "isYoung":false,
    "fullName":true
  },

  {
    "id":552,
    "surname":"Нуртаев",
    "name":"Серик",
    "patronymic": "Болаткулович",
    "wedding":true,
    "uzatu":false,
    "sex":"M",
    "spouse":551,
    "isYoung":false,
    "fullName":true
  },

  {
    "id":553,
    "surname":"Ушкемпиров",
    "name":"Атажан",
    "wedding":true,
    "uzatu":false,
    "sex":"M",
    "spouse":554,
    "isYoung":false,
    "fullName":true
  },

  {
    "id":554,
    "surname":"Жолжаноева",
    "name":"Данеля",
    "wedding":true,
    "uzatu":false,
    "sex":"W",
    "spouse":553,
    "isYoung":false,
    "fullName":true
  },

  {
    "id":555,
    "surname":"Актай",
    "name":"Мирас",
    "wedding":true,
    "uzatu":false,
    "sex":"M",
    "spouse":null,
    "isYoung":false,
    "fullName":true
  },

  {
    "id":556,
    "surname":"Актай",
    "name":"Алимжан",
    "wedding":true,
    "uzatu":false,
    "sex":"M",
    "spouse":null,
    "isYoung":false,
    "fullName":true
  },

  {
    "id":557,
    "surname":"Касымова",
    "name":"Михра",
    "patronymic":"Құдағи",
    "wedding":true,
    "uzatu":false,
    "sex":" W",
    "spouse":null,
    "isYoung":false,
    "fullName":true
  },

  {
    "id":558,
    "surname":"Джумалиев",
    "name":"Рустем",
    "patronymic":"Құда",
    "wedding":true,
    "uzatu":false,
    "sex":"M",
    "spouse":559,
    "isYoung": false,
    "fullName":true
  },

  {
    "id":559,
    "surname":"Джумалиева",
    "name":"Айнаш",
    "patronymic":"Құдағи",
    "wedding":true,
    "uzatu":false,
    "sex":"W",
    "spouse":558,
    "isYoung": false,
    "fullName":true
  },

  {
    "id":560,
    "surname":"Актай",
    "name":"Ансар",
    "wedding":true,
    "uzatu":false,
    "sex":"M",
    "spouse":null,
    "isYoung":true,
    "fullName":false
  },

  {
    "id":561,
    "surname":"Аронова",
    "name":"Ирина",
    "patronymic":"Петровна",
    "wedding":true,
    "uzatu":false,
    "sex":"W",
    "spouse":null,
    "isYoung":false,
    "fullName":true
  },

  {
    "id":562,
    "surname":"Абильмажинов",
    "name":"Айдос",
    "wedding":true,
    "uzatu":false,
    "sex":"M",
    "spouse":null,
    "isYoung":false,
    "fullName":false
  },

  {
    "id":563,
    "surname":"Абильмажинова",
    "name":"Дилара",
    "wedding":true,
    "uzatu":false,
    "sex":"W",
    "spouse":null,
    "isYoung":true,
    "fullName":false
  },

  {
    "id":564,
    "surname":"Абильмажинов",
    "name":"Олжас",
    "wedding":true,
    "uzatu":false,
    "sex":"M",
    "spouse":null,
    "isYoung":true,
    "fullName":false
  },

  {
    "id":565,
    "surname":"Захиддинов",
    "name":"Фазлиддин",
    "wedding":true,
    "uzatu":false,
    "sex":"M",
    "spouse":566,
    "isYoung":true,
    "fullName":false
  },

  {
    "id":566,
    "surname":"Захиддинов",
    "name":"Даяна",
    "wedding":true,
    "uzatu":false,
    "sex":"W",
    "spouse":565,
    "isYoung":true,
    "fullName":false
  },

  {
    "id":567,
    "surname":"Каскеева",
    "name":"Айнура",
    "wedding":true,
    "uzatu":false,
    "sex":"W",
    "spouse":null,
    "isYoung":false,
    "fullName":false
  },

  {
    "id":568,
    "surname":"Конурбаева",
    "name":"Нурбике",
    "wedding":true,
    "uzatu":false,
    "sex":"W",
    "spouse":null,
    "isYoung":false,
    "fullName":false
  },

  {
    "id":569,
    "surname":"Конурбаева",
    "name":"Марал",
    "patronymic":"Тате",
    "wedding":true,
    "uzatu":false,
    "sex":"W",
    "spouse":null,
    "isYoung":false,
    "fullName":true
  },

  {
    "id":570,
    "surname":"Баймужанова",
    "name":"Алтын",
    "wedding":true,
    "uzatu":false,
    "sex":"W",
    "spouse":null,
    "isYoung":false,
    "fullName":false
  },

  {
    "id":571,
    "surname":"Кожахметова",
    "name":"Нурсулу",
    "patronymic":"Кунашовна",
    "wedding":true,
    "uzatu":false,
    "sex":"W",
    "spouse":null,
    "isYoung":false,
    "fullName":true
  },

  {
    "id":572,
    "surname":"Омарова",
    "name":"Асель",
    "patronymic":"Кунашовна",
    "wedding":true,
    "uzatu":false,
    "sex":"W",
    "spouse":1572,
    "isYoung":false,
    "fullName":false
  },

  {
    "id":1572,
    "surname":"Мурат",
    "name":"Ерхан",
    "wedding":true,
    "uzatu":false,
    "sex":"M",
    "spouse":572,
    "isYoung":false,
    "fullName":false
  },

  {
    "id":573,
    "surname":"Омарова",
    "name":"Лязат",
    "wedding":true,
    "uzatu":false,
    "sex":"W",
    "spouse":null,
    "isYoung":false,
    "fullName":false
  },

  {
    "id":574,
    "surname":"Султанова",
    "name":"Карлыгаш",
    "wedding":true,
    "uzatu":false,
    "sex":"W",
    "spouse":null,
    "isYoung":false,
    "fullName":false
  },

  {
    "id":575,
    "surname":"Какимов",
    "name":"Канат",
    "wedding":true,
    "uzatu":false,
    "sex":"M",
    "spouse":576,
    "isYoung":false,
    "fullName":false
  },

  {
    "id":576,
    "surname":"Какимова",
    "name":"Алтын",
    "wedding":true,
    "uzatu":false,
    "sex":"W",
    "spouse":575,
    "isYoung":false,
    "fullName":false
  },

  {
    "id":577,
    "surname":"Токсанов",
    "name":"Алмаз",
    "wedding":true,
    "uzatu":false,
    "sex":"M",
    "spouse":578,
    "isYoung":false,
    "fullName":false
  },

  {
    "id":578,
    "surname":"Мусаева",
    "name":"Айнур",
    "wedding":true,
    "uzatu":false,
    "sex":"W",
    "spouse":577,
    "isYoung":false,
    "fullName":false
  },

  {
    "id":579,
    "surname":"Ибраев",
    "name":"Серик",
    "wedding":true,
    "uzatu":false,
    "sex":"M",
    "spouse":580,
    "isYoung":false,
    "fullName":false
  },

  {
    "id":580,
    "surname":"Ибраева",
    "name":"Жанна",
    "wedding":true,
    "uzatu":false,
    "sex":"W",
    "spouse":579,
    "isYoung":false,
    "fullName":false
  },

  {
    "id":581,
    "surname":"Джаниева",
    "name":"Роза",
    "wedding":true,
    "uzatu":false,
    "sex":"W",
    "spouse": null,
    "isYoung":false,
    "fullName":false
  },

  {
    "id":582,
    "surname":"Хамиев",
    "name":"Ардак",
    "wedding":true,
    "uzatu":false,
    "sex":"M",
    "spouse": 583,
    "isYoung":false,
    "fullName":false
  },

  {
    "id":583,
    "surname":"Абишева",
    "name":"Айжан",
    "wedding":true,
    "uzatu":false,
    "sex":"W",
    "spouse": 582,
    "isYoung":false,
    "fullName":false
  },

  {
    "id":584,
    "surname":"Форлини",
    "name":"Роберто",
    "wedding":true,
    "uzatu":false,
    "sex":"M",
    "spouse": 585,
    "isYoung":false,
    "fullName":false
  },

  {
    "id":585,
    "surname":"Форлини",
    "name":"Светлана",
    "wedding":true,
    "uzatu":false,
    "sex":"W",
    "spouse": 584,
    "isYoung":false,
    "fullName":false
  },

  {
    "id":586,
    "surname":"Усенова",
    "name":"Гульнара",
    "wedding":true,
    "uzatu":false,
    "sex":"W",
    "spouse": null,
    "isYoung":false,
    "fullName":false
  },

  {
    "id":587,
    "surname":"Капаргазина",
    "name":"Роза",
    "wedding":true,
    "uzatu":false,
    "sex":"W",
    "spouse": null,
    "isYoung":false,
    "fullName":false
  },

  {
    "id":588,
    "surname":"Муканов",
    "name":"Галимат",
    "wedding":true,
    "uzatu":false,
    "sex":"M",
    "spouse": 589,
    "isYoung":false,
    "fullName":false
  },

  {
    "id":589,
    "surname":"Муканова",
    "name":"Бейбетгуль",
    "wedding":true,
    "uzatu":false,
    "sex":"W",
    "spouse": 588,
    "isYoung":false,
    "fullName":false
  },

  {
    "id":590,
    "surname":"Дельдекбаев",
    "name":"Еркын",
    "wedding":true,
    "uzatu":false,
    "sex":"M",
    "spouse": 591,
    "isYoung":false,
    "fullName":false
  },

  {
    "id":591,
    "surname":"Дельдекбаева",
    "name":"Нургуль",
    "wedding":true,
    "uzatu":false,
    "sex":"W",
    "spouse": 590,
    "isYoung":false,
    "fullName":false
  },

  {
    "id":592,
    "surname":"Ергалиева",
    "name":"Айбаршин",
    "wedding":true,
    "uzatu":false,
    "sex":"W",
    "spouse": null,
    "isYoung":false,
    "fullName":false
  },

  {
    "id":593,
    "surname":"Еркебаев",
    "name":"Аким",
    "wedding":true,
    "uzatu":false,
    "sex":"M",
    "spouse": 594,
    "isYoung":false,
    "fullName":false
  },

  {
    "id":594,
    "surname":"Еркебаева",
    "name":"Арай",
    "wedding":true,
    "uzatu":false,
    "sex":"W",
    "spouse": 593,
    "isYoung":false,
    "fullName":false
  },

  {
    "id":595,
    "surname":"Раисов",
    "name":"Бауржан",
    "wedding":true,
    "uzatu":false,
    "sex":"M",
    "spouse": 596,
    "isYoung":false,
    "fullName":false
  },

  {
    "id":596,
    "surname":"Утешова",
    "name":"Анара",
    "wedding":true,
    "uzatu":false,
    "sex":"W",
    "spouse": 595,
    "isYoung":false,
    "fullName":false
  },

  {
    "id":597,
    "surname":"Жайлыбаева",
    "name":"Раушан",
     "patronymic":"Тате",
    "wedding":true,
    "uzatu":false,
    "sex":"W",
    "spouse": null,
    "isYoung":false,
    "fullName":true
  },

  {
    "id":598,
    "surname":"Нуралы",
    "name":"Акжан",
    "wedding":true,
    "uzatu":false,
    "sex":"W",
    "spouse": null,
    "isYoung":false,
    "fullName":false
  },

  {
    "id":599,
    "surname":"Еркебаева",
    "name":"Динара",
    "wedding":true,
    "uzatu":false,
    "sex":"W",
    "spouse": null,
    "isYoung":false,
    "fullName":false
  },

  {
    "id":600,
    "surname":"Еркебаева",
    "name":"Лунара",
    "wedding":true,
    "uzatu":false,
    "sex":"W",
    "spouse": 601,
    "isYoung":false,
    "fullName":false
  },

  {
    "id":601,
    "surname":"Абельдинов",
    "name":"Азамат",
    "wedding":true,
    "uzatu":false,
    "sex":"M",
    "spouse": 600,
    "isYoung":false,
    "fullName":false
  },

  {
    "id":602,
    "surname":"Калиева",
    "name":"Жанна",
    "wedding":true,
    "uzatu":false,
    "sex":"W",
    "spouse": null,
    "isYoung":false,
    "fullName":false
  },

  {
    "id":603,
    "surname":"Нуретдин",
    "name":"Еспол",
    "wedding":true,
    "uzatu":false,
    "sex":"M",
    "spouse": 604,
    "isYoung":false,
    "fullName":false
  },

  {
    "id":604,
    "surname":"Каршибаева",
    "name":"Сандугаш",
    "wedding":true,
    "uzatu":false,
    "sex":"W",
    "spouse": 603,
    "isYoung":false,
    "fullName":false
  },
  {
    "id":605,
    "surname":"Сарин",
    "name":"Аманжан",
    "wedding":false,
    "uzatu":true,
    "sex":"M",
    "spouse": null,
    "isYoung":false,
    "fullName":false
  },
  {
    "id":606,
    "surname":"Казбаев",
    "name":"Смайыл",
    "wedding":false,
    "uzatu":true,
    "sex":"M",
    "spouse": null,
    "isYoung":false,
    "fullName":false
  },

  {
    "id":607,
    "surname":"Тамашкул",
    "name":"Диас",
    "wedding":true,
    "uzatu":false,
    "sex":"M",
    "spouse": null,
    "isYoung":true,
    "fullName":false
  },

  {
    "id":608,
    "surname":"Зекенова",
    "name":"Гуля",
    "wedding":true,
    "uzatu":false,
    "sex":"W",
    "spouse": null,
    "isYoung":false,
    "fullName":false
  },

  {
    "id":609,
    "surname":"Нургаликова",
    "name":"Аида",
    "wedding":true,
    "uzatu":false,
    "sex":"W",
    "spouse": null,
    "isYoung":false,
    "fullName":false
  },

  {
    "id":610,
    "surname":"Ускенова",
    "name":"Адина",
    "wedding":true,
    "uzatu":false,
    "sex":"W",
    "spouse": null,
    "isYoung":true,
    "fullName":false
  },

  {
    "id":611,
    "surname":"Нургаликов",
    "name":"Сатыбалды",
    "wedding":true,
    "uzatu":false,
    "sex":"M",
    "spouse": 612,
    "isYoung":false,
    "fullName":false
  },

  {
    "id":612,
    "surname":"Нургаликова",
    "name":"Раушан",
    "wedding":true,
    "uzatu":false,
    "sex":"W",
    "spouse": 611,
    "isYoung":false,
    "fullName":false
  },
 ]
